# Generated by Django 3.1.7 on 2021-04-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remito_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remito',
            old_name='fechaEntrega',
            new_name='fechaIngreso',
        ),
    ]
