# Generated by Django 3.1.7 on 2021-04-03 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0003_auto_20210403_0042'),
        ('administrador', '0005_auto_20210403_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='oti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.ordentrabajo', unique=True),
        ),
    ]
