# Generated by Django 3.1.7 on 2021-04-04 19:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0003_auto_20210403_0042'),
        ('users', '0001_initial'),
        ('administrador', '0007_auto_20210403_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('informacion', models.CharField(blank=True, max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('oti', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.ordentrabajo')),
            ],
        ),
    ]
