# Generated by Django 3.1.7 on 2021-05-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_factura_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='tipo',
        ),
    ]
