# Generated by Django 3.1.7 on 2021-04-01 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerente', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('nroSerie', models.CharField(max_length=100)),
                ('fechaIngreso', models.CharField(max_length=100)),
                ('estadoEquipo', models.CharField(max_length=100)),
                ('fechaEstEqui', models.CharField(max_length=100)),
                ('estadoPresupuesto', models.CharField(max_length=100)),
                ('fechaEstPresu', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gerente.cliente')),
                ('tecnico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='TareasOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('idProducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.ordentrabajo')),
            ],
        ),
    ]
