# Generated by Django 3.1.7 on 2021-03-23 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerente', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('nroSerie', models.CharField(max_length=100)),
                ('fechaIngreso', models.DateField()),
                ('estadoEquipo', models.CharField(max_length=100, null=True)),
                ('fechaEstEqui', models.DateField(null=True)),
                ('estadoPresupuesto', models.CharField(max_length=100, null=True)),
                ('fechaEstPresu', models.DateField(null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerente.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
