# Generated by Django 3.1.7 on 2021-04-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('gerente', '0002_equipobackup_ordentrabajo'),
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerente.cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estadoEquipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estadoPresupuesto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaEstEqui',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaEstPresu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaIngreso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='nroSerie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
