# Generated by Django 3.1.7 on 2021-04-03 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_auto_20210401_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaIngreso',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
